# Generated by Django 2.2.1 on 2019-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='contact',
            field=models.EmailField(default='@abc.edu', max_length=254),
            preserve_default=False,
        ),
    ]
