# Generated by Django 2.2.1 on 2019-06-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0005_mocktest1_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='acronym',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.college', to_field='acronym'),
        ),
    ]
