# Generated by Django 2.2.1 on 2019-06-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0006_auto_20190607_1002'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='student',
        #     name='DOB',
        # ),
        migrations.AddField(
            model_name='student',
            name='db_folder',
            field=models.CharField(default='@abc.edu', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dropped_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mocktest1',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.student', to_field='db_folder'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
