# Generated by Django 2.2.1 on 2019-06-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0007_auto_20190607_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
    ]
