# Generated by Django 2.2.1 on 2019-06-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('season', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('team1', models.CharField(max_length=64)),
                ('team2', models.CharField(max_length=64)),
                ('toss_won', models.CharField(max_length=64)),
                ('toss_lost', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
                ('dl_applied', models.IntegerField()),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=64)),
                ('venue_of_match', models.CharField(max_length=64)),
                ('umpire1', models.CharField(max_length=64)),
                ('umpire2', models.CharField(max_length=64)),
                ('umpire3', models.CharField(max_length=64)),
            ],
        ),
    ]
