# Generated by Django 2.2.1 on 2019-06-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default='2000-10-10'),
        ),
    ]
