# Generated by Django 2.2.1 on 2019-06-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0003_auto_20190617_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
    ]
