# Generated by Django 2.2.1 on 2019-06-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0004_remove_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='umpire3',
            field=models.CharField(default='Empty', max_length=64),
        ),
    ]
