# Generated by Django 2.2.1 on 2019-06-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0005_auto_20190617_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='umpire3',
        ),
    ]
