# Generated by Django 2.2.1 on 2019-06-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0006_remove_match_umpire3'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='umpire3',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_of_match',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_won',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
