# Generated by Django 2.2.1 on 2019-06-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0008_auto_20190617_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match_id',
            new_name='match',
        ),
    ]
