# Generated by Django 2.2.1 on 2019-06-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0009_auto_20190617_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match',
            new_name='mid',
        ),
    ]
